project:
  type: website
  output-dir: docs

website:
  title: "Jimmy Narang"
  google-analytics: "G-QWJG2V9Q5P"
  navbar:
    title: false
    #background: primary
    background: "#a6a8a688"
    search: true
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - patents.qmd
      - icon: file-pdf-fill
        text: CV
        href: "https://www.dropbox.com/scl/fi/jdqxo8hqqjb3hqfkro0kn/CV_2024-_Academic.pdf?rlkey=aoiklp6hkgh9lvebtlpefarft&dl=0"  

format:
  html:
    page-layout: full
    theme:
      light: flatly # First theme is default
      dark: darkly      
    css: styles.css
    toc: true
    fontsize: 14px
    link-external-icon: true
    link-external-newwindow: true
    #linkcolor: "#18bc9c"
    email-obfuscation: javascript
