project:
  type: website
  output-dir: docs

website:
  title: "Jimmy Narang"
  google-analytics: "G-QWJG2V9Q5P"
  navbar:
    title: false
    background: primary
    search: true
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - patents.qmd
      - icon: file-pdf-fill
        text: CV
        href: "https://www.dropbox.com/s/6lw7n5hzq9gi0d2/CV_Jimmy_Narang_2023.pdf?dl=0"  

format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
    fontsize: 14px
    link-external-icon: true
    link-external-newwindow: true
    linkcolor: "#18bc9c"
    email-obfuscation: javascript
