project:
  type: website
  output-dir: docs

website:
  title: "Jimmy Narang"
  google-analytics: "G-QWJG2V9Q5P"
  navbar:
    title: false
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - patents.qmd

format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
    fontsize: 14px
    #link-external-icon: true
    link-external-newwindow: true
    linkcolor: "#18bc9c"
    email-obfuscation: javascript
