project:
  type: website
  output-dir: docs

website:
  title: "Jimmy Narang"
  navbar:
    title: false
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - patents.qmd

format:
  html:
    page-layout: full
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
    #fontsize: 12px
    #link-external-icon: true
    link-external-newwindow: true
    linkcolor: "#18bc9c"
    email-obfuscation: javascript
